# See https://docs.docker.com/compose/compose-file/
services:
  frontend:
    build: .
    hostname: frontend
    container_name: hans-frontend-web
    environment:
      # BACKEND
      - HANS_BACKEND_HOST=${HANS_BACKEND_HOST}
      - HANS_BACKEND_PORT=${HANS_BACKEND_PORT}
      - HANS_BACKEND_PROTOCOL=${HANS_BACKEND_PROTOCOL}
      - HANS_BACKEND_HOST_URL=${HANS_BACKEND_HOST_URL}
      - HANS_BACKEND_CONNID=${HANS_BACKEND_CONNID}
      # FRONTEND
      - HANS_FRONTEND_HOST=${HANS_FRONTEND_HOST}
      - HANS_FRONTEND_PORT=${HANS_FRONTEND_PORT}
      - HANS_FRONTEND_PROTOCOL=${HANS_FRONTEND_PROTOCOL}
      - HANS_FRONTEND_HOST_URL=${HANS_FRONTEND_HOST_URL}
      - HANS_FRONTEND_SSL_PORT=${HANS_FRONTEND_SSL_PORT}
      - HANS_FRONTEND_CONNID=${HANS_FRONTEND_CONNID}
      - HANS_FRONTEND_API_PORT=${HANS_FRONTEND_API_PORT}
      - HANS_FRONTEND_API_HOST=${HANS_FRONTEND_API_HOST}
      - HANS_FRONTEND_API_PRODUCTION_MODE=${HANS_FRONTEND_API_PRODUCTION_MODE}
      # ML-BACKEND
      - HANS_ML_BACKEND_AIRFLOW_HOST=${HANS_ML_BACKEND_AIRFLOW_HOST}
      - HANS_ML_BACKEND_AIRFLOW_PORT=${HANS_ML_BACKEND_AIRFLOW_PORT}
      - HANS_ML_BACKEND_AIRFLOW_POSTFIX=${HANS_ML_BACKEND_AIRFLOW_POSTFIX}
      - HANS_ML_BACKEND_AIRFLOW_ROOT_USER=${HANS_ML_BACKEND_AIRFLOW_ROOT_USER}
      - HANS_ML_BACKEND_AIRFLOW_ROOT_PASSWORD=${HANS_ML_BACKEND_AIRFLOW_ROOT_PASSWORD}
      # ASSETDB
      - HANS_BACKEND_ASSETDB_HOST=${HANS_BACKEND_ASSETDB_HOST:-assetdb}
      - HANS_BACKEND_ASSETDB_PORT=${HANS_BACKEND_ASSETDB_PORT:-9001}
      - HANS_BACKEND_ASSETDB_ROOT_USER=${HANS_BACKEND_ASSETDB_ROOT_USER:-minio}
      - HANS_BACKEND_ASSETDB_ROOT_PASSWORD=${HANS_BACKEND_ASSETDB_ROOT_PASSWORD:-minio123}
      # MEDIADB
      - HANS_BACKEND_MEDIADB_HOST=${HANS_BACKEND_MEDIADB_HOST:-mediadb}
      - HANS_BACKEND_MEDIADB_PORT=${HANS_BACKEND_MEDIADB_PORT:-9000}
      - HANS_BACKEND_MEDIADB_ROOT_USER=${HANS_BACKEND_MEDIADB_ROOT_USER:-minio}
      - HANS_BACKEND_MEDIADB_ROOT_PASSWORD=${HANS_BACKEND_MEDIADB_ROOT_PASSWORD:-minio123}
      # METADB
      - HANS_BACKEND_METADB_HOST=${HANS_BACKEND_METADB_HOST:-metadb}
      - HANS_BACKEND_METADB_PORT=${HANS_BACKEND_METADB_PORT:-27017}
      - HANS_BACKEND_METADB_ROOT_USER=${HANS_BACKEND_METADB_ROOT_USER:-root}
      - HANS_BACKEND_METADB_ROOT_PASSWORD=${HANS_BACKEND_METADB_ROOT_PASSWORD:-password}
      - HANS_BACKEND_METADB_DATABASE=${HANS_BACKEND_METADB_DATABASE:-meta}
      # OPENSEARCH
      - HANS_BACKEND_OPENSEARCH_HOST=${HANS_BACKEND_OPENSEARCH_HOST:-searchengine}
      - HANS_BACKEND_OPENSEARCH_PORT=${HANS_BACKEND_OPENSEARCH_PORT:-9200}
      - HANS_BACKEND_OPENSEARCH_ROOT_USER=${HANS_BACKEND_OPENSEARCH_ROOT_USER:-admin}
      - HANS_BACKEND_OPENSEARCH_ROOT_PASSWORD=${HANS_BACKEND_OPENSEARCH_ROOT_PASSWORD:-admin}
      - HANS_BACKEND_OPENSEARCH_STANDARD_INDEX=${HANS_BACKEND_OPENSEARCH_STANDARD_INDEX:-lecture_result_index_multilang_v01}
      - HANS_BACKEND_OPENSEARCH_VECTOR_INDEX=${HANS_BACKEND_OPENSEARCH_VECTOR_INDEX:-lecture_result_vector_index_v01}
      - HANS_BACKEND_OPENSEARCH_SLIDES_VECTOR_INDEX=${HANS_BACKEND_OPENSEARCH_SLIDES_VECTOR_INDEX:-lecture_slides_result_vector_index_v01}
      - HANS_BACKEND_OPENSEARCH_SUMMARIES_VECTOR_INDEX=${HANS_BACKEND_OPENSEARCH_SUMMARIES_VECTOR_INDEX:-lecture_summaries_result_vector_index_v01}
      # ML-SERVICES LLM
      - HANS_ML_SERVICE_LLM_HOST=${HANS_ML_SERVICE_LLM_HOST:-host.docker.internal}
      - HANS_ML_SERVICE_LLM_PORT=${HANS_ML_SERVICE_LLM_PORT:-8093}
      - HANS_ML_SERVICE_LLM_USER=${HANS_ML_SERVICE_LLM_USER:-admin}
      - HANS_ML_SERVICE_LLM_PASSWORD=${HANS_ML_SERVICE_LLM_PASSWORD:-admin}
      - HANS_ML_SERVICE_LLM_MODEL_ID=${HANS_ML_SERVICE_LLM_MODEL_ID:-mistralai/Mixtral-8x7B-Instruct-v0.1}
      - HANS_ML_SERVICE_LLM_MAX_NEW_TOKENS=${HANS_ML_SERVICE_LLM_MAX_NEW_TOKENS:-32768}
      # ML-SERVICES VLLM
      - HANS_ML_SERVICE_VLLM_HOST=${HANS_ML_SERVICE_VLLM_HOST:-host.docker.internal}
      - HANS_ML_SERVICE_VLLM_PORT=${HANS_ML_SERVICE_VLLM_PORT:-8092}
      - HANS_ML_SERVICE_VLLM_USER=${HANS_ML_SERVICE_VLLM_USER:-admin}
      - HANS_ML_SERVICE_VLLM_PASSWORD=${HANS_ML_SERVICE_VLLM_PASSWORD:-admin}
      - HANS_ML_SERVICE_VLLM_MODEL_ID=${HANS_ML_SERVICE_VLLM_MODEL_ID:-mistralai/Pixtral-12B-2409}
      - HANS_ML_SERVICE_VLLM_MAX_NEW_TOKENS=${HANS_ML_SERVICE_VLLM_MAX_NEW_TOKENS:-32768}
      # ML-SERVICES EMBEDDING
      - HANS_ML_SERVICE_EMBEDDING_HOST=${HANS_ML_SERVICE_EMBEDDING_HOST:-host.docker.internal}
      - HANS_ML_SERVICE_EMBEDDING_PORT=${HANS_ML_SERVICE_EMBEDDING_PORT:-8094}
      - HANS_ML_SERVICE_EMBEDDING_USER=${HANS_ML_SERVICE_EMBEDDING_USER:-admin}
      - HANS_ML_SERVICE_EMBEDDING_PASSWORD=${HANS_ML_SERVICE_EMBEDDING_PASSWORD:-admin}
      # ML-SERVICES TRANSLATION
      - HANS_ML_SERVICE_TRANSLATION_HOST=${HANS_ML_SERVICE_TRANSLATION_HOST:-host.docker.internal}
      - HANS_ML_SERVICE_TRANSLATION_PORT=${HANS_ML_SERVICE_TRANSLATION_PORT:-8098}
      - HANS_ML_SERVICE_TRANSLATION_USER=${HANS_ML_SERVICE_TRANSLATION_USER:-admin}
      - HANS_ML_SERVICE_TRANSLATION_PASSWORD=${HANS_ML_SERVICE_TRANSLATION_PASSWORD:-admin}
      # ML-SERVICES ORCHESTRATOR
      - HANS_ML_SERVICE_ORCHESTRATOR_LLM=${HANS_ML_SERVICE_ORCHESTRATOR_LLM:-False}
      - HANS_ML_SERVICE_ORCHESTRATOR_VLLM=${HANS_ML_SERVICE_ORCHESTRATOR_VLLM:-False}
      - HANS_ML_SERVICE_ORCHESTRATOR_TRANSLATION=${HANS_ML_SERVICE_ORCHESTRATOR_TRANSLATION:-False}
      - HANS_ML_SERVICE_ORCHESTRATOR_EMBEDDING=${HANS_ML_SERVICE_ORCHESTRATOR_EMBEDDING:-False}
      - HANS_ML_SERVICE_ORCHESTRATOR_HOST=${HANS_ML_SERVICE_ORCHESTRATOR_HOST:-host.docker.internal}
      - HANS_ML_SERVICE_ORCHESTRATOR_PORT=${HANS_ML_SERVICE_ORCHESTRATOR_PORT:-8035}
      - HANS_ML_SERVICE_ORCHESTRATOR_USER=${HANS_ML_SERVICE_ORCHESTRATOR_USER:-admin}
      - HANS_ML_SERVICE_ORCHESTRATOR_PASSWORD=${HANS_ML_SERVICE_ORCHESTRATOR_PASSWORD:-admin}
      - HANS_ML_SERVICE_ORCHESTRATOR_LLM_ROUTE=${HANS_ML_SERVICE_ORCHESTRATOR_LLM_ROUTE:-llm_service}
      - HANS_ML_SERVICE_ORCHESTRATOR_VLLM_ROUTE=${HANS_ML_SERVICE_ORCHESTRATOR_VLLM_ROUTE:-vllm_service}
      - HANS_ML_SERVICE_ORCHESTRATOR_TRANSLATION_ROUTE=${HANS_ML_SERVICE_ORCHESTRATOR_TRANSLATION_ROUTE:-translation_service}
      - HANS_ML_SERVICE_ORCHESTRATOR_EMBEDDING_ROUTE=${HANS_ML_SERVICE_ORCHESTRATOR_EMBEDDING_ROUTE:-embedding_service}
    expose:
      - ${HANS_FRONTEND_API_PORT:-5001}:${HANS_FRONTEND_API_PORT:-5001}
    ports:
      - ${HANS_FRONTEND_PORT:-80}:${HANS_FRONTEND_PORT:-80}
      - ${HANS_FRONTEND_SSL_PORT:-443}:${HANS_FRONTEND_SSL_PORT:-443}
    restart: always
    networks:
      - frontend-tier
    # Only needed if ml-backend is hosted on same system as frontend and backend
    extra_hosts:
      - "${DOCKER_HOST_GATEWAY_IP:-host.docker.internal}:host-gateway"

networks:
  frontend-tier:
    name: ${HANS_FB_NETWORK_NAME}
    external: true
