# OpenSearch Dashboards
# Version: 2.19.0
# Release notes: https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.19.0.md
FROM opensearchproject/opensearch-dashboards:2.19.0
